name: Tower CLI continuous build
# read more here
# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - '*'
      - '!refs/tags/.*'
    tags-ignore:
      - '*'

jobs:

  linux-image:
    name: Tower CLI build Linux native image
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          architecture: x64

      - name: Tests
        run: ./gradlew cleanTest test

      - name: Tests reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: linux-test-reports
          path: build/reports/tests/test/

      - name: Build Native Image
        run: ./gradlew nativeImage

      - name: Extract version
        run: echo "::set-output name=VERSION::$(cat src/main/resources/META-INF/build-info.properties | grep "version=" | cut -d= -f2)_$(cat src/main/resources/META-INF/build-info.properties | grep "commitId=" | cut -d= -f2)"
        id: extract-version

      - name: Upload linux native image artifact
        uses: actions/upload-artifact@v2
        with:
          name: towr_${{ steps.extract-version.outputs.VERSION }}_linux
          path: build/graal/towr

      - name: Binary tests
        run: ./gradlew cleanTest test
        env:
          TOWER_CLI: build/graal/towr

      - name: Binary tests reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: linux-binary-test-reports
          path: build/reports/tests/test/

  mac-image:
    name: Tower CLI build Mac native image
    runs-on: macos-latest
    timeout-minutes: 90

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          architecture: x64

      - name: Tests
        run: ./gradlew cleanTest test

      - name: Tests reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: mac-test-reports
          path: build/reports/tests/test/

      - name: Build Native Image
        run: ./gradlew nativeImage

      - name: Extract version
        run: echo "::set-output name=VERSION::$(cat src/main/resources/META-INF/build-info.properties | grep "version=" | cut -d= -f2)_$(cat src/main/resources/META-INF/build-info.properties | grep "commitId=" | cut -d= -f2)"
        id: extract-version

      - name: Upload Mac native image artifact
        uses: actions/upload-artifact@v2
        with:
          name: towr_${{ steps.extract-version.outputs.VERSION }}_mac
          path: build/graal/towr

      - name: Binary tests
        run: ./gradlew cleanTest test
        env:
          TOWER_CLI: build/graal/towr

      - name: Binary tests reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: mac-binary-test-reports
          path: build/reports/tests/test/

  windows-image:
    name: Tower CLI build Windows native image
    runs-on: windows-latest
    timeout-minutes: 90

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          architecture: x64

      - name: Tests
        run: ./gradlew cleanTest test

      - name: Tests reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: windows-test-reports
          path: build/reports/tests/test/

      - name: Build Native Image
        run: ./gradlew nativeImage

      - name: Extract version
        run: echo "::set-output name=VERSION::$(cat src/main/resources/META-INF/build-info.properties | grep "version=" | cut -d= -f2)_$(cat src/main/resources/META-INF/build-info.properties | grep "commitId=" | cut -d= -f2)"
        id: extract-version

      - name: Upload Windows native image artifact
        uses: actions/upload-artifact@v2
        with:
          name: towr_${{ steps.extract-version.outputs.VERSION }}_windows
          path: build/graal/towr.exe

      - name: Binary tests
        run: ./gradlew cleanTest test
        env:
          TOWER_CLI: build/graal/towr.exe

      - name: Binary tests reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: windows-binary-test-reports
          path: build/reports/tests/test/


