name: Tower CLI continuous build
# read more here
# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - '*'
      - '!refs/tags/.*'
    tags-ignore:
      - '*'  

jobs:

  linux-image:
    name: Tower CLI build Linux native image
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - name: Environment
      run: env | sort 

    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        architecture: x64

    - name: Tests
      run: ./gradlew cleanTest test

    - name: Tests reports
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: linux-test-reports
        path: build/reports/tests/test/

    - name: Build Native Image
      run: ./gradlew nativeImage

    - name: Linux native image
      uses: actions/upload-artifact@v2
      with:
        name: linux-native-image
        path: build/graal/towr

    - name: Binary tests
      run: TOWER_CLI=build/graal/towr ./gradlew cleanTest test

    - name: Binary tests reports
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: linux-binary-test-reports
        path: build/reports/tests/test/

  mac-image:
    name: Tower CLI build Mac native image
    runs-on: macos-latest
    timeout-minutes: 90

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          architecture: x64

      - name: Tests
        run: ./gradlew cleanTest test

      - name: Tests reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: mac-test-reports
          path: build/reports/tests/test/

      - name: Build Native Image
        run: ./gradlew nativeImage

      - name: Mac native image
        uses: actions/upload-artifact@v2
        with:
          name: mac-native-image
          path: build/graal/towr

      - name: Binary tests
        run: TOWER_CLI=build/graal/towr ./gradlew cleanTest test

      - name: Binary tests reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: mac-binary-test-reports
          path: build/reports/tests/test/

  windows-image:
    name: Tower CLI build Windows native image
    runs-on: windows-latest
    timeout-minutes: 90

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          architecture: x64

      - name: Tests
        run: ./gradlew cleanTest test

      - name: Tests reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: windows-test-reports
          path: build/reports/tests/test/

      - name: Build Native Image
        run: ./gradlew nativeImage

      - name: Windows native image
        uses: actions/upload-artifact@v2
        with:
          name: windows-native-image
          path: build/graal/towr.exe

      - name: Binary tests
        run: TOWER_CLI=build/graal/towr.exe ./gradlew cleanTest test

      - name: Binary tests reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: windows-binary-test-reports
          path: build/reports/tests/test/


